# Overview

- torch is basically **numpy**, but on the gpu
- torch has variants/counterparts of numpy
- torch has additional *helper functions*

In [2]:
import torch
import torchvision

tensor([10,  3])


## Init Tensors

- A tensor is just a multidimentional array

In [10]:
x = torch.tensor([5,3])
y = torch.tensor([2,1])

print(x*y)

tensor([10,  3])


## Zero out a tensor value
- just another calculation that can be done

In [3]:
x = torch.zeros([2,5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [5]:
x.shape

torch.Size([2, 5])

In [13]:
y = torch.rand([2,5])

In [14]:
y

tensor([[0.1752, 0.6663, 0.0953, 0.9519, 0.8387],
        [0.0474, 0.5973, 0.6117, 0.7145, 0.8412]])

## Reshaping Things

- Numpy has a *reshape* function, (also possibly tensorflow)
- torch uses a function/method called *view*

### EX:

- want to flatten something (an image)
- thing is a 2x5 array (2x5 pixels)
- have to *flatten* image to feed to a nueral network
- will turn 2x5 into 1x10

In [15]:
y.view([1,10])

tensor([[0.1752, 0.6663, 0.0953, 0.9519, 0.8387, 0.0474, 0.5973, 0.6117, 0.7145,
         0.8412]])

In [16]:
y

tensor([[0.1752, 0.6663, 0.0953, 0.9519, 0.8387],
        [0.0474, 0.5973, 0.6117, 0.7145, 0.8412]])

In [17]:
y = y.view([1,10])

In [18]:
y

tensor([[0.1752, 0.6663, 0.0953, 0.9519, 0.8387, 0.0474, 0.5973, 0.6117, 0.7145,
         0.8412]])